In [1]:
import numpy as np

## Примеры создания массивов

In [8]:
lst = [i for i in range(20)] # Создание списка из чисел от 0 до 19 при помощи списочного выражения
arr = np.array(lst) # Список становится одномерным массивом numpy

In [9]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
zero_arr = np.zeros((5, 5)) # Создание квадратной нулевой матрицы размером 5

In [16]:
zero_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
ones_arr = np.ones((2, 4)) # Создание матрицы, заполненной единицами, размером 2 на 4

In [18]:
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
arange_arr = np.arange(10).reshape(5, 2) # Создание одномерной матрицы с элементами от 0 до 9, затем ее превращение в матрицу 5 на 2

In [46]:
arange_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
diag = np.eye(3) # Создание диагональной матрицы размером 3

In [28]:
diag

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Демонстрация атрибутов

In [37]:
diag

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
diag.shape # Атрибут, хранящий кортеж количества элементов массива по каждой оси

(3, 3)

In [33]:
diag.dtype # Атрибут, хранящий тип данных, содержащихся в массиве

dtype('float64')

In [35]:
diag.ndim # Размерность массива (кол-во осей)

2

## Примеры индексирования и срезов

In [36]:
arange_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
arange_arr[1, 0] # Элемент массива, находящийся в первой строке, нулевом столбце

2

In [49]:
arange_arr[2:, 1:] # Подмассив (строки, начиная со второй, столбцы, начиная с первого)

array([[5],
       [7],
       [9]])

## Примеры векторных операций и базовых статистик

In [53]:
arange_arr * arange_arr # Поэлементное умножение массивов

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
arr_mean = np.mean(arr) # Среднее массива

arr_min = np.min(arr) # Мин. элемент массива
arr_max = np.max(arr) # Макс. элемент массива
norm_arr = (arr - arr_min) / (arr_max - arr_min) # Нормализация данных

print(f'Среднее массива: {arr_mean}\nМакс. элемент массива: {arr_max}\nМин. элемент массива: {arr_min}\nНормализованный массив: {norm_arr}')

Среднее массива: 9.5
Макс. элемент массива: 19
Мин. элемент массива: 0
Нормализованный массив: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
